#! /bin/sh 

# fix java apps
wmname LG3D &
export _JAVA_AWT_WM_NONREPARENTING=1

#workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

#border colors
bspc config focused_border_color "#c60505"
#border width, gap, ratio etc...
bspc config border_width         1 
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#bspc config single_monocle 	 true
bspc config focus_follows_pointer true 

#rules for programs
bspc rule -a "jadx-gui" state=floating
bspc rule -a "burp-StartBurp" state=tiled
bspc rule -a "Zathura" state=tiled
bspc rule -a "Maltego state"=floating #rectangle=1280x800+160+50
bspc rule -a "Authy Desktop" state=tiled 
bspc rule -a "tk" state=floating 
bspc rule -a "Tk" state=floating 
bspc rule -a "megasync" state=tiled
bspc rule -a "pavucontrol" state=floating rectangle=1280x800+160+50
#bspc rule -a "*" title="tui-network" state=floating rectangle=1280x800+160+50


#scripts
"$HOME/.config/bspwm/start"

#(cursor theme is in ~/.icons and you "select it" in the ~/.Xresources file)
xsetroot -cursor_name left_ptr &
