;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

; default color scheme
[colors]
; Use the 'og color scheme' as base
background = #000000
background-alt = #282A2E
foreground = #ffffff
primary = #A90A0A
secondary = #8ABEB7
alert = #A54242
disabled = #707880

; Optionally merge some specific color for other purposes
red = #c30505
green = #43a047
yellow = #fdd835
occupied = #7f0808
inactive = #121212
numberinact = #4D4D4D
numberact = #BDBDBD


[bar/main]
width = 100%
height = 40
;radius = 6
; dpi = 96

margin-top=0
margin-bottom=0

fixed-center=true

offset-x = 0%
offset-y = 0%

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 0pt

border-size = 0pt
border-color = #00000000

padding-left = 0
padding-right = 0

module-margin = 0

separator = "|" 
separator-foreground = ${colors.disabled}

font-0 = "FiraCode Nerd Font Mono:pixelsize=12:style=Regular;3"
;font-1 = "xFiraCode NFM:pixelsize=16:style=Regular;3"

modules-left = xworkspaces filesystem memory cpu temperature myip
modules-center = date
modules-right =  mytarget autocolor caps pulseaudio backlight bat0 bat1 systray pwmenu   

;cursor-click = pointer
;cursor-scroll = ns-resize

enable-ipc = true

; wm-restack = generic
wm-restack = bspwm
; wm-restack = i3

; override-redirect = true

[module/myip]
type = custom/script
exec = ~/.config/polybar/_scripts/myip.sh
format = <label>
label = %output%
label-padding = 1
click-left = ~/.config/polybar/_scripts/myip.sh --copy



[module/mytarget]
type = custom/script
exec = ~/.config/polybar/_scripts/mytarget.sh
format  = <label>
label = %output%
label-padding = 1
click-left = ~/.config/polybar/_scripts/mytarget.sh --copy



[module/systray]
type = internal/tray
format-margin = 1pt
tray-spacing = 1pt

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-foreground = ${colors.numberact}
label-active-background = ${colors.occupied}
label-active-padding = 1

label-occupied = %name%
label-occupied-foreground = ${colors.occupied}
label-occupied-background = ${colors.inactive}
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.numberinact}
label-empty-background = ${colors.inactive}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /

label-mounted = %{F#A90A0A}%mountpoint%%{F-} %percentage_free:2%%
label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}

[module/autocolor]
type = custom/script
exec = echo "  "
click-left = python3 ~/.config/polybar/_scripts/color_picker_gui.py

[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = "VOL"
format-volume-prefix-foreground = ${colors.primary}
format-volume = <label-volume>

label-volume = %{A1:~/.config/polybar/_scripts/pavucontrol.sh:}%percentage:4:3%%%{A}

label-muted = muted
label-muted-foreground = ${colors.red}

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

label-layout = %layout%
label-layout-foreground = ${colors.primary}

label-indicator-padding = 1
label-indicator-margin = 1
label-indicator-foreground = ${colors.background}
label-indicator-background = ${colors.secondary}


[module/caps]
; capslock indicator 
type = internal/xkeyboard
blacklist-0 = num lock
format=<label-indicator>
label-indicator-background = ${colors.red}
label-indicator-on-capslock = A
label-indicator-on-capslock-background = ${colors.red}
label-indicator-off-capslock = a
label-indicator-on-capslock-padding = 2
label-indicator-off-capslock-padding = 2

[module/memory]
type = internal/memory
interval = 2
format-prefix = RAM
format-prefix-foreground = ${colors.primary}
label = %percentage_used:3%%
warn-percentage = 50
format-warn = <label-warn>
format-warn-background=${colors.red}
format-warn-prefix = RAM
label-warn = %percentage_used:3%%


[module/cpu]
type = internal/cpu

interval = 2
format = <label> 
format-prefix = CPU
format-prefix-foreground = ${colors.primary}
label = %percentage:3%%

warn-percentage = 50
format-warn = <label-warn>
format-warn-background=${colors.red}
format-warn-prefix = CPU
label-warn = %percentage:3%%


[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %{A1:~/.config/polybar/_scripts/tui_net.sh:}%{F#F0C674}%ifname%%{F#707880} x%{A}


[module/wlan]
inherit = network-base
interface-type = wireless
label-connected = %{A1:~/.config/polybar/_scripts/tui_net.sh:}%{F#F0C674}󰤨 %{F-}%local_ip%%{A}

[module/eth]
inherit = network-base
interface-type = wired
label-connected = %{A1:~/.config/polybar/_scripts/tui_net.sh:}%{F#F0C674}󰈀 %{F-}%local_ip%%{A}

[module/vpn]
type = custom/script
exec = echo vpn
exec-if = pgrep -x openvpn
interval = 5
format-underline = #268bd2
format-prefix = "🖧 "
format-prefix-foreground = #5b

[module/date]
type = internal/date
interval = 1

date = %d/%m/%y %{F#A90A0A} %a %{F-} %I:%M:%S
label = %date%
#label = "%{A1:$HOME/.config/polybar/_scripts/mycal.py:}%date%%{A}"

label-foreground = ${colors.foreground}

[module/backlight]
;type = internal/xbacklight
type = internal/backlight
; Use the following command to list available cards:
; $ ls -1 /sys/class/backlight/
card = intel_backlight
;card = amdgpu_bl0
format = <label> 
label = %{F#A90A0A}BKL%{F-}%percentage:4:3%% 
enable-scroll=true


[module/bat0]
type = internal/battery

full-at = 95
low-at = 20

; Use the following command to list batteries and adapters:
; $ ls -1 /sys/class/power_supply/
battery = BAT0
adapter = AC

poll-interval = 5
;time-format = %H:%M
format-charging = <label-charging>
format-discharging = <ramp-capacity> <label-discharging>

label-charging = 󱐋 %percentage%%
label-discharging = %percentage%%
label-full = 󱊦 
label-low = 󱃍!!!

label-charging-padding = 0
label-discharging-padding = 0
label-full-padding = 1
label-low-padding = 0

ramp-capacity-0 = 󰁻
ramp-capacity-1 = 󰁽
ramp-capacity-2 = 󰁿
ramp-capacity-3 = 󰂁
ramp-capacity-4 = 󰁹
bar-capacity-width = 10
animation-charging-framerate = 750
animation-discharging-0 = 󰁹
animation-discharging-1 = 󰂁
animation-discharging-2 = 󰁿
animation-discharging-3 = 󰁽
animation-discharging-4 = 󰁻
animation-discharging-framerate = 500
animation-low-0 = 󱃍!!
animation-low-1 = 󱃍!
animation-low-framerate = 200


[module/bat1]
type = internal/battery

full-at = 95
low-at = 20

; Use the following command to list batteries and adapters:
; $ ls -1 /sys/class/power_supply/
battery = BAT1
adapter = AC

poll-interval = 5
;time-format = %H:%M
format-charging = <label-charging>
format-discharging = <ramp-capacity> <label-discharging>

label-charging = 󱐋 %percentage%%
label-discharging = %percentage%%
label-full = 󱊦 
label-low = 󱃍!!!

label-charging-padding = 0
label-discharging-padding = 0
label-full-padding = 1
label-low-padding = 0

ramp-capacity-0 = 󰁻
ramp-capacity-1 = 󰁽
ramp-capacity-2 = 󰁿
ramp-capacity-3 = 󰂁
ramp-capacity-4 = 󰁹
bar-capacity-width = 10
animation-charging-framerate = 750
animation-discharging-0 = 󰁹
animation-discharging-1 = 󰂁
animation-discharging-2 = 󰁿
animation-discharging-3 = 󰁽
animation-discharging-4 = 󰁻
animation-discharging-framerate = 500
animation-low-0 = 󱃍!!
animation-low-1 = 󱃍!
animation-low-framerate = 200

[module/temperature]
type = internal/temperature

interval = 1
thermal-zone = 0
hwmon-path = /sys/devices/virtual/thermal/thermal_zone0/hwmon0/temp1_input 
warn-temperature = 60
units = true
format = <label>
format-warn = <label-warn>
format-warn-background = ${colors.red}
label = %temperature-c%
label-warn = %temperature-c%
format-padding = 1
format-warn-padding = 1


[module/pwmenu]
type = custom/text
content = "x"
content-padding=2
content-foreground = ${colors.primary}
click-left = ~/.config/polybar/_scripts/pwmenu.sh &


[settings]
;screenchange-reload = true
;pseudo-transparency = true

; vim:ft=dosini
